### ISSUE TITLE
Error connecting to channel I TypeError

### ISSUE THREAD

**Issue by LordCage** [anonymousthing/listen.moe-djs#10]
![capture](https://cloud.githubusercontent.com/assets/20691232/21579953/50274354-cf9d-11e6-8568-28af37ba6ae9.PNG)

**Not sure if i did something wrong here, Sometimes it will correct itself after restarting x amount of times.**

**Comment by iCrawl** [comment]
This shouldn't happen if you use the d.js version that comes with the bot in the package.json and not install the latest d.js obviously.
