### ISSUE TITLE
bot offline

### ISSUE THREAD

**Issue by darkilegeek** [anonymousthing/listen.moe-djs#11]
the bot are offline and don't listen the command 
![listen](https://cloud.githubusercontent.com/assets/27288542/24956400/bcff6936-1f87-11e7-9e3c-55235bb95516.PNG)

**Comment by bitnimble** [comment]
Yes, we are aware that there are issues on our end with the hosting. 

However, this is not an issue with the codebase (and this isn't even the correct codebase anymore, we've moved to https://github.com/WeebDev/listen.moe-discord) so I'm closing this ticket.
